apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ include "system-upgrade-controller.serviceAccountName" . }}
  labels:
    {{- include "system-upgrade-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ include "system-upgrade-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
