apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "system-upgrade-controller.fullname" . }}-env
  namespace: system-upgrade
  labels:
    {{- include "system-upgrade-controller.labels" . | nindent 4 }}
data: {{ .Values.configEnv | toYaml }}
