apiVersion: v1
kind: Secret
metadata:
  name: openstack-clouds
  namespace: system-upgrade
type: Opaque
data:
  clouds.yaml: |
    clouds:
      openstack:
        auth:
          auth_url: "https://openstack.example.com/v3"
          application_credential_id: "secret"
          application_credential_secret: "secret"
        auth_type: "v3applicationcredential"
        identity_api_version: 3
        interface: "public"
        region_name: "RegionOne"
